CREATE TABLE product
(id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL UNIQUE,
 code VARCHAR(255) NOT NULL UNIQUE,
 cost DECIMAL NOT NULL
 );

INSERT INTO product (name, code, cost) VALUES ("Bag", "TN6857345", 100);